from enum import IntEnum, auto
from functools import total_ordering


@total_ordering
class Token(IntEnum):
    LOWEST_PRECEDENCE = auto()
    EOF = auto()
    LET = auto()
    CONST = auto()
    IDENTIFIER = auto()
    LITERAL = auto()
    SEMICOLON = auto()
    ASSIGN = auto()
    INT = auto()
    FLOAT = auto()
    CHAR = auto()
    STRING = auto()
    NULL = auto()
    IF = auto()
    ELSE = auto()
    LPAREN = auto()
    RPAREN = auto()
    LBRACE = auto()
    RBRACE = auto()
    TRUE = auto()
    FALSE = auto()
    FUNCTION = auto()
    OR = auto()
    AND = auto()
    EQUAL = auto()
    NOTEQUAL = auto()
    LESS = auto()
    LESSEQUAL = auto()
    GREATER = auto()
    GREATEREQUAL = auto()
    NOT = auto()
    PLUS = auto()
    MINUS = auto()
    ASTERISK = auto()
    SLASH = auto()
    FOR = auto()
    WHILE = auto()
    CONTINUE = auto()
    BREAK = auto()
    COMMA = auto()
    RETURN = auto()
